name: Publish to GitHub Packages
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: "Release version"

      snapshot_version:
        type: string
        description: "Snapshot version"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Prepare release
        run: mvn build-helper:parse-version versions:set -DnewVersion=${{ github.event.inputs.message }} -DgenerateBackupPoms=false
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

